version: '3.9'
services:
  redis:
    image: 'redis/redis-stack:latest'
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
    environment:
      - REDIS_ARGS="--notify-keyspace-events Ksg"
      - REDIS_ARGS="--requirepass test"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure